name: Environment variables

on: 
  workflow_dispatch:

env:
  DAY: Friday

jobs:
  greet-people:
    runs-on: ubuntu-latest
    env: 
      GREETING: Hello
      MESSAGE: I love you
      
    steps:
      - name: "Say hello"
        env:
          NAME: Anshu
        run: echo "$GREETING! $NAME. I have a message for you - $MESSAGE"
